import type { FeelState } from './feel-state';

/** Request payload sent to Claude API for vocal coaching feedback */
interface AICoachRequest {
  /** The polyrhythm being practiced */
  polyrhythmId: string;

  /** Session tempo in BPM */
  bpm: number;

  /** User's current self-reported feel state */
  feelState: FeelState;

  /**
   * Array of onset timestamps (ms relative to session start).
   * Generated by on-device audio analysis — no raw audio sent.
   */
  onsetTimestamps: number[];

  /** Expected beat timestamps for comparison */
  expectedTimestamps: number[];

  /** Which layer the user was singing/tapping */
  targetLayer: 'A' | 'B';
}

/** Response from Claude API for vocal coaching */
interface AICoachResponse {
  /** 2-3 sentence coaching feedback */
  feedback: string;

  /** Specific area to focus on: 'timing' | 'consistency' | 'feel' | 'breathing' */
  focusArea: string;

  /** Optional: suggested BPM adjustment */
  suggestedBpm: number | null;

  /** Optional: suggested exercise to try next */
  suggestedExercise: string | null;
}

/** Raw onset data from on-device audio analysis */
interface VocalOnsetData {
  /** Onset timestamps in milliseconds, relative to recording start */
  onsets: number[];

  /** Confidence score for each onset (0.0 to 1.0) */
  confidences: number[];

  /** Duration of the recording in milliseconds */
  recordingDuration: number;

  /** Sample rate used for analysis */
  sampleRate: number;
}

/**
 * Assigns a rhythm layer to a body part for independence training.
 * Used in Body Layer Mode (P1).
 */
interface BodyLayerAssignment {
  /** Which rhythm layer this assignment controls */
  layer: 'A' | 'B';

  /** Body part assigned to this layer */
  bodyPart: 'voice' | 'clapping' | 'right-hand' | 'left-hand' | 'foot-stomp';

  /** Input method for detecting this body part's rhythm */
  inputMethod: 'tap' | 'microphone' | 'accelerometer';
}

/** Request to generate custom mnemonics */
interface MnemonicRequest {
  /** The polyrhythm to generate mnemonics for */
  polyrhythmId: string;

  /** User's chosen theme category */
  themeCategory: 'animals' | 'food' | 'sports' | 'names' | 'custom';

  /** Custom theme string if themeCategory is 'custom' */
  customTheme: string | null;

  /** The exact syllable pattern to match, e.g. [3, 2] for 3:2 */
  syllablePattern: number[];
}

/** Response with generated mnemonic options */
interface MnemonicResponse {
  /** 2-3 mnemonic options that fit the syllable count */
  mnemonics: Array<{
    /** The mnemonic phrase */
    phrase: string;

    /** Syllable breakdown showing alignment to beats */
    syllableBreakdown: string;

    /** Which theme it matches */
    theme: string;
  }>;
}

export type {
  AICoachRequest,
  AICoachResponse,
  VocalOnsetData,
  BodyLayerAssignment,
  MnemonicRequest,
  MnemonicResponse,
};
